preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  highcapable-maven-releases:
    url: https://raw.githubusercontent.com/HighCapable/maven-repository/main/repository/releases

plugins:
  com.android.application:
    alias: android-application
    version: 8.5.2
  com.android.library:
    alias: android-library
    version-ref: com.android.application
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.0.21
  org.jetbrains.dokka:
    alias: kotlin-dokka
    version: 1.9.20
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.30.0

libraries:
  com.highcapable.betterandroid:
    ui-component:
      version: 1.0.6
    ui-extension:
      version: 1.0.6
    system-extension:
      version: 1.0.2
  com.highcapable.yukireflection:
    api:
      version: 1.0.3
  androidx.core:
    core:
      version: 1.15.0
    core-ktx:
      version-ref: <this>::core
  androidx.appcompat:
    appcompat:
      version: 1.7.0
  com.google.android.material:
    material:
      # Workaround for a bug in version 1.12.0
      version: 1.11.0
      auto-update: false
  androidx.constraintlayout:
    constraintlayout:
      version: 2.2.0
  junit:
    junit:
      version: 4.13.2
  androidx.test.ext:
    junit:
      version: 1.2.1
  androidx.test.espresso:
    espresso-core:
      version: 3.6.1